# Generated by Django 5.1.6 on 2025-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='blockchain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
