# Generated by Django 4.2.11 on 2025-02-11 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.AddField(
            model_name='electiontitle',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electiontitle',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vote',
            name='election_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.electiontitle'),
        ),
        migrations.AlterField(
            model_name='electiontitle',
            name='title',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
