# Generated by Django 4.2.11 on 2025-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_vote_election_electiontitle_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontitle',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', max_length=10),
        ),
    ]
