# Generated by Django 4.2.11 on 2025-02-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_electiontitle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontitle',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electiontitle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
