# Generated by Django 5.1.6 on 2025-02-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_electiontitle_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiontitle',
            name='status',
        ),
    ]
