# Generated by Django 5.1.6 on 2025-02-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_electiontitle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontitle',
            name='status',
            field=models.CharField(default='Not Scheduled', max_length=20),
        ),
    ]
