# Generated by Django 5.1.6 on 2025-02-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_electiontitle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiontitle',
            name='status',
        ),
    ]
