# Generated by Django 5.1.6 on 2025-02-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_remove_electiontitle_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
